name: Deploy Frontend

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Build imagem Docker
        run: docker-compose build frontend

      - name: Subir containers
        run: docker-compose up -d frontend
